vim.keymap.set("n", "<leader>ff", "<Cmd>FzfLua files<CR>")
vim.keymap.set("n", "<leader>b", "<Cmd>FzfLua buffers<CR>")
vim.keymap.set("n", "<leader>gr", "<Cmd>FzfLua live_grep<CR>")
vim.keymap.set("n", "<leader>gd", "<Cmd>FzfLua lsp_definitions<CR>")
vim.keymap.set("n", "<leader>fr", "<Cmd>FzfLua lsp_references<CR>")
